version: '3'

services:
    nginx:
        image: nginx
        depends_on:
            - phpfpm
        restart: always
        ports:
            - 80:80
        links:
            - phpfpm
        volumes:
            - ./engine:/var/www/webasyst
            - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    phpfpm:
        build: php-fpm
        depends_on:
          - mysql
        environment:
          - TIMEZONE=${TIMEZONE}
        restart: always
        ports:
            - 9000:9000
        volumes:
            - ./engine:/var/www/webasyst
    mysql:
        image: mysql:5.7.36
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQL_DATABASE
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_PASSWORD=$MYSQL_PASSWORD
        volumes:
            - ./mysql:/var/lib/mysql
    pma:
        image: phpmyadmin
        restart: always
        links:
            - mysql
        ports:
            - 8080:80
        environment:
            - PMA_HOST=mysql
            - PMA_ARBITARY=1