services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  pma:
    image: phpmyadmin:latest
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  phpfpm:
    build:
      context: ./.docker/php-fpm
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    depends_on:
      - mysql
    restart: unless-stopped
    volumes:
      - ./engine:/var/www/webasyst:rw
      - ./.docker/php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:latest
    depends_on:
      - phpfpm
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./engine:/var/www/webasyst:ro
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.docker/nginx/fastcgi_params:/etc/nginx/fastcgi_params:ro

volumes:
  mysql_data:
    driver: local

networks:
  default:
    driver: bridge
